version: '3'

services: 

    frontend:
        image: node:10
        container_name: web
        ports: 
            - 80:3000
        volumes:
            - ./web/.:.
        networks: 
            - app-network

    backend:
        image: node:10
        container_name: API REST
        environment:
            - APP_PORT=3333
            - APP_DEBUG=false        
        ports: 
            - 443:3333
        volumes:
            - ./backend/.:.
        networks: 
            - app-network
    
networks:
    app-network:
        driver: bridge
              