version: '3'

services: 

    frontend:
        build: ./frontend/.
        container_name: web
        ports: 
            - 80:3000
        volumes:
            - ./frontend:/web
        networks: 
            - app-network

    backend:
        build: ./backend/.
        container_name: backend       
        ports: 
            - 80:3333
        volumes: 
            - ./backend:/app
        networks: 
            - app-network
            # - database-network
        
    
networks:
    app-network:
        driver: bridge
    # database-network:
    #     driver: bridge
              